from pathlib import Path

SCHEDULES_FILE = Path("user_config.json")

LOCATIONS_PATH = Path("Files/1A_locations.csv")                  # location_id, lat, lon
ID_TO_LOC_PATH = Path("Files/1B_identifier_location_map.csv")    # identifier, location_id

META_PATH = Path("Files/4_CA_Metadata_RepSample.csv")            # optional
IDX_ALL_PATH = Path("Files/personalization_indices_by_home_all_years.parquet")

PEAKS_ALL_PATH = Path("Files/schedule_clock_peaks_all_years.parquet")  # optional
FP_HOME_ALL_PATH = Path("Files/schedule_setpoint_home_summary_all_years.parquet")  # optional

TIMING_HOURLY_PATH = Path("Files/schedule_location_timing_hourly.parquet")
SUGGESTIONS_PATH = Path("Files/schedule_name_suggestions.parquet")

TIN_MODEL_PATH = Path("Files/thermal_model_xgboost_allyears.pkl")  # .pkl/.joblib OR xgb booster (.json/.ubj/.bin)
RUNTIME_MODEL_DIR = Path("Files/runtime_model_step3_enduse")  # XGBoost runtime predictor model directory

# 2R2C thermal profiles (optional - for displaying building thermal parameters)
R2C2_PROFILES_PATH = Path("Files/2r2c_profiles_qc_year=2023.parquet")  # or .csv
# If you have multiple years, point to a directory or merge them into one file

# Clustering profiles (generated by create_user_profiles_clustering.py)
CLUSTER_PROFILES_PATH = Path("Files/cluster_profiles_by_year.parquet")
HOME_CLUSTERS_PATH = Path("Files/home_year_clusters.parquet")

# Historical outdoor temperature data (parquet files by location_id and year)
# Structure: OUTDOOR_TEMPS_DIR / location_id=XXXX / year=YYYY.parquet
DATA_CACHE_DIR = Path("data_cache")
OUTDOOR_TEMPS_DIR = DATA_CACHE_DIR / "3_Outdoor_temps"
OUTDOOR_LOCATIONS_PATH = LOCATIONS_PATH
OUTDOOR_TEMPS_GDRIVE_FILE_ID = "1hbEU0HZEOEebA2pDQpG-Kv3UeDORE-Ek"

# ---------- Open-Meteo ----------
GEOCODE_URL = "https://geocoding-api.open-meteo.com/v1/search"
FORECAST_URL = "https://api.open-meteo.com/v1/forecast"

# ---------- Feature order must match training ----------
TIN_FEATURES = [
    "outdoor_temp",
    "outdoor_temp_lag1",
    "outdoor_humidity",
    "heat_sp",
    "cool_sp",
    "deadband",
    "temp_diff",
    "temp_diff_lag1",
    "indoor_temp_lag1",
    "hvac_heat",
    "hvac_cool",
    "hvac_auto",
    "hvac_off",
    "heat_effectively_off",
    "cool_effectively_off",
    "hvac_effectively_idle",
    "hour_sin",
    "hour_cos",
    "month_sin",
    "month_cos",
    "is_weekend",
    "building_age_yrs",
    "floor_area_sqft",
    "climate_3B",
    "climate_4B",
    "climate_3C",
    "climate_2B",
    "climate_5B",
    "climate_4C",
    "climate_6B",
    "bldg_Townhouse",
    "bldg_Apartment",
    "bldg_Detached",
    "bldg_Other",
    "bldg_Row House",
    "bldg_Semi-Detached",
    "bldg_Condominium",
    "bldg_Multi-plex",
    "bldg_Loft",
]

MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
               "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

# =========================================================
# STYLING (Ecobee-inspired)
# =========================================================
BASE_BG = "#111827"
WHITE = "#F9FAFB"
MUTED = "#F2F2F2"
ACCENT = "#F97316"
COOL_BLUE = "#60A5FA"
TEAL = "#22C55E"
